import type { Locale } from "../shell/i18n";

const RENTS = [650, 750, 850, 950, 1100, 1250, 1400, 1600, 1850, 2100, 2400, 2800, 3200, 3800, 4500];

const rents = (thousands: string, unit: string) =>
  RENTS.map((n) => `${String(n).replace(/\B(?=(\d{3})+(?!\d))/g, thousands)} ${unit}`);

const ES = {
  level: "Niv",
  floors: "Pisos",
  record: "Récord",
  workers: "obreros",
  floor: "Planta",
  place: "COLOCAR",
  placeHintKey: "ESPACIO para colocar el piso",
  placeHintTouch: "Toca COLOCAR para construir",
  heliHintKey: "¡CLIC para destruir el helicóptero!",
  heliHintTouch: "¡TOCA para destruir el helicóptero!",
  camKey: "¡CLIC!",
  camTouch: "¡TOCA!",
  camLabel: "CAM 01 - FRONTERA",
  noWorkers: "¡SIN OBREROS! ¡ABRE LA FRONTERA!",
  fewWorkers: (n: number) => `¡SOLO ${n} OBREROS! ¡ABRE LA FRONTERA!`,
  strike: "HELICÓPTEROS EN HUELGA",
  agreement: "CONVENIO COLECTIVO ACTIVO",
  unionBlock: "SINDICALISTA",
  collapseQuote: "¡Ya os lo decía yo!",
  climberHintKey: "¡CLIC en los alpinistas antes de que rompan la torre!",
  climberHintTouch: "¡TOCA a los alpinistas antes de que rompan la torre!",
  climberQuotes: [
    "¡Nos tapáis el Pic!",
    "¡Esto era una vía ferrata!",
    "¡Devolvednos las vistas!",
    "Aquí había un refugio",
  ],
  prices: [
    ...rents(".", "EUR/mes"),
    "LUJO",
    "SUPER LUJO",
    "MEGA LUJO",
    "ULTRA LUJO",
    "PUJOL EDITION",
    "CRIPTO BRO",
    "INFLUENCER",
    "LE TOCÓ EL GORDO",
    "PILOTO F1",
    "JEQUE",
    "NIVEL KALDEA",
    "CON PLAZA DE PARKING",
    "BORDA REFORMADA",
    "ÁTICO ILEGAL",
    "MÁS CARO QUE MÓNACO",
    "RIÑÓN + HIPOTECA",
    "VENDE EL COCHE",
    "DUERME EN EL COCHE",
    "VUELVE A ESPAÑA",
    "PRECIO A CONSULTAR",
  ],
  quotes: [
    "En mis tiempos esto era un prado...",
    "Otra torre más, ¿dónde aparco yo?",
    "Eso no aguanta ni un invierno",
    "¿Y eso cuánto cuesta? ¡Borda!",
    "Antes aquí había vacas",
    "Mi nieto no puede pagar ni un estudio",
    "¡Más alto que el Kaldea!",
    "Esto va a dar sombra a mi huerto",
    "¿Dónde queda el campo de petanca?",
    "Yo cuando era joven...",
  ],
  polQuotes: [
    "¡Esa torre da demasiada sombra!",
    "Necesitamos más parkings, no pisos",
    "¡Derriben eso inmediatamente!",
    "Aquí se necesita un centro comercial",
    "¿Tiene licencia de obras?",
  ],
  description:
    "Construye la torre más alta de Andorra mientras los viejos miran y los helicópteros del GOAT (Grupo Organizado Anti Torres) intentan derribarla.",
  tagline: "Construye la torre más alta de Andorra",
  lostCollapse: "La torre se ha derrumbado",
  lostMiss: "El piso ha caído al vacío",
  floorsUnit: "pisos",
  newRecord: "¡Nuevo récord!",
  howTo: "Cómo jugar",
  keySpace: "ESPACIO",
  keyClick: "CLIC",
  keyTap: "TOCA",
  chipBorder: "FRONTERA",
  helpPlace: "Coloca el piso. Cuanto más preciso, menos se recorta. Si aciertas perfecto, suena ¡FATALITY!",
  helpShoot:
    "Destruye los helicópteros del GOAT (Grupo Organizado Anti Torres) que bombardean la torre. Tienen una diana roja.",
  helpBorder:
    "Pulsa la cámara CCTV para abrir la frontera. Los obreros peruanos entran y te permiten seguir construyendo.",
  helpUnion:
    "Bloque dorado especial. Activa una bonificación: o los helicópteros hacen huelga, o la frontera se abre sola con obreros extra.",
  chipClimbers: "ALPINISTAS",
  helpClimbers:
    "Bajan en cuerda por los lados y rompen la torre a golpes de piolet, quitándole vida. Dispárales y saldrán rebotando.",
  helpFooter:
    "Cada 10 pisos aparece una plataforma nueva con el ancho original. La velocidad nunca se reinicia. Sin obreros no puedes construir: ¡abre la frontera! La torre tiene 5 puntos de vida. Si los helicópteros y los alpinistas la destruyen, Game Over.",
  helpKeys: "P o Esc: pausa. M: silenciar.",
};

export type Texts = typeof ES;

const CA: Texts = {
  level: "Niv",
  floors: "Pisos",
  record: "Rècord",
  workers: "obrers",
  floor: "Planta",
  place: "COL·LOCAR",
  placeHintKey: "ESPAI per col·locar el pis",
  placeHintTouch: "Toca COL·LOCAR per construir",
  heliHintKey: "CLIC per destruir l'helicòpter!",
  heliHintTouch: "TOCA per destruir l'helicòpter!",
  camKey: "CLIC!",
  camTouch: "TOCA!",
  camLabel: "CAM 01 - FRONTERA",
  noWorkers: "SENSE OBRERS! OBRE LA FRONTERA!",
  fewWorkers: (n: number) => `NOMÉS ${n} OBRERS! OBRE LA FRONTERA!`,
  strike: "HELICÒPTERS EN VAGA",
  agreement: "CONVENI COL·LECTIU ACTIU",
  unionBlock: "SINDICALISTA",
  collapseQuote: "Ja us ho deia jo!",
  climberHintKey: "CLIC als alpinistes abans que trenquin la torre!",
  climberHintTouch: "TOCA els alpinistes abans que trenquin la torre!",
  climberQuotes: [
    "Ens tapeu el Pic!",
    "Això era una via ferrada!",
    "Torneu-nos les vistes!",
    "Aquí hi havia un refugi",
  ],
  prices: [
    ...rents(".", "EUR/mes"),
    "LUXE",
    "SUPER LUXE",
    "MEGA LUXE",
    "ULTRA LUXE",
    "PUJOL EDITION",
    "CRIPTO BRO",
    "INFLUENCER",
    "LI HA TOCAT LA GROSSA",
    "PILOT F1",
    "XEIC",
    "NIVELL KALDEA",
    "AMB PLAÇA DE PÀRKING",
    "BORDA REFORMADA",
    "ÀTIC IL·LEGAL",
    "MÉS CAR QUE MÒNACO",
    "RONYÓ + HIPOTECA",
    "VEN EL COTXE",
    "DORM AL COTXE",
    "TORNA A ESPANYA",
    "PREU A CONSULTAR",
  ],
  quotes: [
    "En el meu temps això era un prat...",
    "Una altra torre, on aparco jo?",
    "Això no aguanta ni un hivern",
    "I això quant costa? Borda!",
    "Abans aquí hi havia vaques",
    "El meu nét no pot pagar ni un estudi",
    "Més alt que el Kaldea!",
    "Això farà ombra al meu hort",
    "On queda el camp de petanca?",
    "Jo quan era jove...",
  ],
  polQuotes: [
    "Aquella torre fa massa ombra!",
    "Necessitem més pàrkings, no pisos",
    "Enderroquin això immediatament!",
    "Aquí es necessita un centre comercial",
    "Té llicència d'obres?",
  ],
  description:
    "Construeix la torre més alta d'Andorra mentre els vells miren i els helicòpters del GOAT (Grup Organitzat Anti Torres) intenten enderrocar-la.",
  tagline: "Construeix la torre més alta d'Andorra",
  lostCollapse: "La torre s'ha ensorrat",
  lostMiss: "El pis ha caigut al buit",
  floorsUnit: "pisos",
  newRecord: "Nou rècord!",
  howTo: "Com jugar",
  keySpace: "ESPAI",
  keyClick: "CLIC",
  keyTap: "TOCA",
  chipBorder: "FRONTERA",
  helpPlace: "Col·loca el pis. Com més precís, menys es retalla. Si l'encertes perfecte, sona FATALITY!",
  helpShoot:
    "Destrueix els helicòpters del GOAT (Grup Organitzat Anti Torres) que bombardegen la torre. Tenen una diana vermella.",
  helpBorder: "Prem la càmera CCTV per obrir la frontera. Els obrers peruans entren i et permeten seguir construint.",
  helpUnion:
    "Bloc daurat especial. Activa una bonificació: o els helicòpters fan vaga, o la frontera s'obre sola amb obrers extra.",
  chipClimbers: "ALPINISTES",
  helpClimbers:
    "Baixen amb corda pels laterals i trenquen la torre a cops de piolet, traient-li vida. Dispara'ls i sortiran rebotant.",
  helpFooter:
    "Cada 10 pisos apareix una plataforma nova amb l'amplada original. La velocitat mai es reinicia. Sense obrers no pots construir: obre la frontera! La torre té 5 punts de vida. Si els helicòpters i els alpinistes la destrueixen, Game Over.",
  helpKeys: "P o Esc: pausa. M: silenciar.",
};

const EN: Texts = {
  level: "Lvl",
  floors: "Floors",
  record: "Best",
  workers: "workers",
  floor: "Floor",
  place: "BUILD",
  placeHintKey: "SPACE to place the floor",
  placeHintTouch: "Tap BUILD to build",
  heliHintKey: "CLICK to shoot down the helicopter!",
  heliHintTouch: "TAP to shoot down the helicopter!",
  camKey: "CLICK!",
  camTouch: "TAP!",
  camLabel: "CAM 01 - BORDER",
  noWorkers: "NO WORKERS! OPEN THE BORDER!",
  fewWorkers: (n: number) => `ONLY ${n} WORKERS LEFT! OPEN THE BORDER!`,
  strike: "HELICOPTERS ON STRIKE",
  agreement: "COLLECTIVE AGREEMENT ACTIVE",
  unionBlock: "UNION REP",
  collapseQuote: "Told you so!",
  climberHintKey: "CLICK the climbers before they break the tower!",
  climberHintTouch: "TAP the climbers before they break the tower!",
  climberQuotes: [
    "You're blocking the peak!",
    "This used to be a via ferrata!",
    "Give us back the view!",
    "There was a mountain hut here",
  ],
  prices: [
    ...rents(",", "EUR/mo"),
    "LUXURY",
    "SUPER LUXURY",
    "MEGA LUXURY",
    "ULTRA LUXURY",
    "PUJOL EDITION",
    "CRYPTO BRO",
    "INFLUENCER",
    "LOTTERY WINNER",
    "F1 DRIVER",
    "SHEIKH",
    "KALDEA LEVEL",
    "PARKING SPACE INCLUDED",
    "RENOVATED BORDA",
    "ILLEGAL PENTHOUSE",
    "PRICIER THAN MONACO",
    "KIDNEY + MORTGAGE",
    "SELL THE CAR",
    "SLEEP IN THE CAR",
    "MOVE BACK TO SPAIN",
    "PRICE ON REQUEST",
  ],
  quotes: [
    "Back in my day this was a meadow...",
    "Another tower? Where do I park now?",
    "That won't survive one winter",
    "How much? That's a whole borda!",
    "There used to be cows here",
    "My grandson can't even afford a studio",
    "Taller than Kaldea!",
    "That's going to shade my vegetable patch",
    "Where did the pétanque court go?",
    "When I was young...",
  ],
  polQuotes: [
    "That tower casts too much shade!",
    "We need more car parks, not flats",
    "Tear that down immediately!",
    "What this spot needs is a shopping mall",
    "Does it even have a building permit?",
  ],
  description:
    "Build the tallest tower in Andorra while the old men watch and the GOAT (Group Organized Against Towers) helicopters try to knock it down.",
  tagline: "Build the tallest tower in Andorra",
  lostCollapse: "The tower came down",
  lostMiss: "The floor fell into the void",
  floorsUnit: "floors",
  newRecord: "New record!",
  howTo: "How to play",
  keySpace: "SPACE",
  keyClick: "CLICK",
  keyTap: "TAP",
  chipBorder: "BORDER",
  helpPlace:
    "Place the floor. The more precise you are, the less gets trimmed off. Nail it perfectly and you'll hear FATALITY!",
  helpShoot:
    "Shoot down the GOAT (Group Organized Against Towers) helicopters bombing your tower. They have a red target.",
  helpBorder: "Hit the CCTV camera to open the border. The Peruvian workers come in and let you keep building.",
  helpUnion:
    "Special golden block. It triggers a bonus: either the helicopters go on strike, or the border opens by itself with extra workers.",
  chipClimbers: "CLIMBERS",
  helpClimbers:
    "They abseil down the sides and smash the tower with ice axes, taking hit points. Shoot them and they bounce away.",
  helpFooter:
    "Every 10 floors a new platform appears at full width. The speed never resets. No workers, no building: open the border! The tower has 5 hit points. If the helicopters and climbers destroy it, Game Over.",
  helpKeys: "P or Esc: pause. M: mute.",
};

export const TEXT: Record<Locale, Texts> = { es: ES, ca: CA, en: EN };
